### ISSUE TITLE
 The "-f" option does not exist. 

### ISSUE THREAD

**Issue by zubairIftikharKwe** [tiagomichaelsousa/LaravelResources#16]
Lumen V 6.3.3
While i'm creating php artisan resources:create Post
On  
**Should I create the seeder for Post?** 
`  The "-f" option does not exist. `

**Comment by tiagomichaelsousa** [comment]
> Lumen V 6.3.3
> While i'm creating php artisan resources:create Post
> On
> **Should I create the seeder for Post?**
> ` The "-f" option does not exist.`

Hi! Thank you for your feedback.
The package was developed only for laravel. Lumen doesn't come with the model generator and you are probably using a third party package to generate your models. With that said, the package that you are using to generate the models probably doesn't come with the same flags as laravel do. That's why `The "-f" option does not exist.`. Try to run the `php artisan make:model --help` to checkout which flags are available for you. 

The option -f is related to the factory for the Post class that you are trying to generate.

Currently the package is executing the artisan command when the model was not found. A solution for this issue is to create a new generator for the `migration`, `factory` and `seeder`.

Feel free to add the feat and submit the PR 🚀

Thank you

**Comment by tiagomichaelsousa** [comment]
Hi @zubairIftikharKwe, i didn't had the time to try the new version on lumen, but now with the v1.7 the **migration**, the **factory** and the **seeders** are being created with stubs and not with the execution of the php artisan command.

You should give it a try now 😉
